### ISSUE TITLE
requirements.txt has conflict item

### ISSUE THREAD

**Issue by eastGrass** [ystkmeg/docker-django-uwsgi-nginx-mysql#24]
```
...
django-debug-toolbar
...
```

delete the duplicate `django-debug-toolbar`, then ok

**Comment by yoshitakameguro** [comment]
Thanks. Fixed [e10268f](https://github.com/yoshitakameguro/docker-django-uwsgi-nginx-mysql/commit/e10268f1fa6dfda64887d88ce369767bc71558dc).
